---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mdo-rule-udr
  name: mdo-rule-udr
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mdo-rule-udr
---
